# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  代码笔记本
subtitle: 加油吧，打工人！
name: 代码笔记本
email: 708851221@qq.com
description: 本站是李长伟的技术学习分享博客。内容涵盖Linux、Java后端技术、Spring Boot、Spring Cloud、微服务架构、中间件使用等相关的学习知识分享。
keywords: Spring,Spring Boot,Spring Cloud,MongoDB,Jvm,Docker,架构,FastDFS,编程,代码,开源,Developer,IT技术博客,Java,Python,Nginx,Gitlab
encoding: "utf-8"
favicon: l_favicon.ico

repository: li708851221/li708851221.github.io
github_url: https://github.com/li708851221
url: https://li708851221.github.io
enforce_ssl: li708851221.github.io

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons
  
# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:
  -
  -
    href: /link.html
    label: 友链
    target: _self

  -
    href: /about.html
    label: 关于
    target: _self


# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /spring-boot.html
    label: Spring Boot
    target: _self

  -
    label: Spring Cloud
    target: _self
    subnav:

      -
        subHref: /spring-cloud.html
        subLabel: SpringCloud

      -
        subHref: /spring-cloud-alibaba.html
        subLabel: Alibaba

  -
    href: /java.html
    label: Java
    target: _self
    subnav:

      -
        subHref: /java-base.html
        subLabel: Java基础

      -
        subHref: /algorithms.html
        subLabel: 数据结构和算法

  -
    href: /linux.html
    label: Linux
    target: _self

  -
    href: /archives.html
    label: Archives
    target: _self




# labels. my blog key words
labels:

  -
    href: /mongodb.html
    label: MongoDB
    target: _blank

  -
    href: /docker.html
    label: Docker
    target: _blank
  -
    href: /fastdfs.html
    label: FastDFS
    target: _blank

  -
    href: /open-source.html
    label: GitHub
    target: _blank

  -
    href: /it.html
    label: IT 
    target: _blank

  -
    href: /python.html
    label: Python  
    target: _blank

  - href: /payment.html
    label: 支付
    target: _self


# selected articles
classes:

  -
    href: /linux/2019/07/20/linux-command.html
    name: Linux常用命令大全
    describe: Linux常用命令备忘

  -
    href: /algorithms.html
    name: 数据结构和算法
    describe: 数据结构和算法之美

  -
    href: /java.html
    name: Java 系列文章
    describe: Java 之根基，Java 程序员必学


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: li708851221
# https://imsun.net/posts/gitment-introduction/
  #gitment:
  #owner: li708851221
  #repo: li708851221.github.io
      #oauth:
      #client_id: 8f5eb7729ed1a53db65c
  #client_secret: 970c224788cda9791799c9d492c7b8faf1e1f92f
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: li708851221
    repo: li708851221.github.io
    clientID: 8f5eb7729ed1a53db65c
    clientSecret: 970c224788cda9791799c9d492c7b8faf1e1f92f
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
